name: Build and publish

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code style with Black
      run: |
        pre-commit install
        pre-commit run --all-files --color always --verbose --show-diff-on-failure

    - name: Test with pytest
      run: scripts/run_tests.sh
