name: Build and publish

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1

    - name: Check style with Black
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit black
        pre-commit install
        pre-commit run --all-files --color always --verbose --show-diff-on-failure

    - name: Install package
      run: |
        poetry env use 3.9
        poetry install

    - name: Test with pytest
      run: poetry run pytest tests/
