# # # # # # # # #
# Source: https://github.com/miloserdova-l/mrob/blob/feature/windows-wheel/.github/workflows/wheels.yml
# # # # # # # # #
name: Build and publish

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Check style with Black
      run: |
        pre-commit install
        pre-commit run --all-files --color always --verbose --show-diff-on-failure

    - name: Test with pytest
      run: poetry run pytest tests/
