name: Pre-commit
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies for pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pre-commit
        run: |
          pre-commit install

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
